name: Scheduled Robot

on:
  schedule:
    - cron: "*/1 * * * *"   # Every 5 minutes

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello Vamshi 🚀 This runs every 5 minutes!"
